# Generated by Django 5.2.8 on 2025-11-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostico',
            old_name='resultado',
            new_name='descripcion',
        ),
    ]
